backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "src/assets/img"
public_folder: "/static/img"

collections: 
  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Name, name: name, widget: string}
      - {label: Position, name: position, widget: number}
      - {label: Path, name: path, widget: hidden}
      - {label: Sections, name: sections, widget: list, fields: [{label: Title, name: title, widget: string}, {label: Name, name: name, widget: string}, {label: Text, name: text, widget: markdown}, {label: Image, name: image_before, widget: image, required: false}]}
  - name: "news" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "News" # Used in the UI, ie.: "New Post"
    folder: "src/content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: Description, name: description, widget: string}
      - {label: Image, name: image, widget: image, required: false}    
      - {label: "Text", name: "body", widget: "markdown"}
  - name: "services" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Courses" # Used in the UI, ie.: "New Post"
    folder: "src/content/courses" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Title, name: title, widget: string}
      - {label: Date, name: termin, widget: string}
      - {label: Price, name: price, widget: string}
      - {label: Position, name: position, widget: number}
      - {label: Description, name: description, widget: string}
      - {label: Image, name: image, widget: image, required: false}      
      - {label: "Text", name: "body", widget: "markdown"}
