backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "src/assets/img"
public_folder: "/static/img"

collections: 
  - name: "pages"
    label: "Seiten"
    folder: "src/content/pages"
    create: false
    delete: false
    fields:
      - {label: Titel, name: title, widget: string}
      - {label: Name, name: name, widget: string}
      - {label: "Position für Sortierreihenfolge", name: position, widget: number}
      - {label: Pfad, name: path, widget: hidden}
      - {label: Sections, name: sections, widget: list, fields: [{label: Title, name: title, widget: string}, {label: Name, name: name, widget: string}, {label: Text, name: text, widget: markdown}, {label: Image, name: image_before, widget: image, required: false, default: ''}]}
  - name: "news" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Aktuelles" # Used in the UI, ie.: "New Post"
    folder: "src/content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Datum für Sortierreihenfolge", name: "date", widget: "datetime"}
      - {label: "Auf Startseite anzeigen bis", name: "frontpageUntil", widget: "datetime"}
      - {label: Kurzbeschreibung, name: description, widget: string}
      - {label: Termin, name: termin, widget: string, required: false, default: ''}
      - {label: Ort, name: place, widget: string, required: false, default: ''}
      - {label: Preis, name: price, widget: string, required: false, default: ''}
      - {label: AnmeldeInformationen, name: subscription, widget: string, required: false, default: ''}
      - {label: Bild, name: image, widget: image, required: false, default: ''}    
      - {label: "Text", name: "body", widget: "markdown"}
  - name: "services" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Kurse" # Used in the UI, ie.: "New Post"
    folder: "src/content/courses" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Titel, name: title, widget: string}
      - {label: Datum, name: termin, widget: string}
      - {label: Kurzbeschreibung, name: description, widget: string}
      - {label: Preis, name: price, widget: string}
      - {label: "Position für Sortierreihenfolge", name: position, widget: number}
      - {label: Bild, name: image, widget: image, required: false, default: ''}      
      - {label: "Text", name: "body", widget: "markdown"}
